seed_everything: 42
trainer:
  logger: true
  checkpoint_callback: null
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints
        filename: checkpoint
        save_top_k: 1
        monitor: val_loss
        mode: min
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  num_nodes: 1
  num_processes: 1
  devices: auto
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 2
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: null
  log_every_n_steps: 50
  accelerator: auto
  strategy: null
  sync_batchnorm: false
  precision: 16
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
  terminate_on_nan: null
model:
  transforms:
    class_path: src.transforms.MNISTTransform
    init_args:
      input_size: 224
      train_mode: true
  eval_transforms:
    class_path: src.transforms.MNISTTransform
    init_args:
      input_size: 224
      train_mode: false
  model_name: mobilenet
  n_classes: 10
data:
  batch_size: 32
  train_data:
    - data/MNIST/train_images.pt
    - data/MNIST/train_labels.pt
  val_data:
    - data/MNIST/val_images.pt
    - data/MNIST/val_labels.pt
  test_data:
    - data/MNIST/test_images.pt
    - data/MNIST/test_labels.pt
ckpt_path: null
